In [0]:
from torchvision import models


In [0]:
a = [1.0, 2.0, 1.0]

In [5]:
a[0]

1.0

In [6]:
a[2]

1.0

In [7]:
import torch # <1>
a = torch.ones(3) # <2>
a

tensor([1., 1., 1.])

In [8]:
a[1]

tensor(1.)

In [9]:
float(a[1])

1.0

In [10]:
a[2] = 2.0
a

tensor([1., 1., 2.])

In [0]:
pts = torch.zeros(6) 
pts[0] = 4.0 
pts[1] = 1.0
pts[2] = 5.0
pts[3] = 3.0
pts[4] = 2.0
pts[5] = 1.0

In [12]:
pts = torch.tensor([4.0, 1.0, 5.0, 3.0, 2.0, 1.0])
pts

tensor([4., 1., 5., 3., 2., 1.])

In [13]:
float(pts[0]), float(pts[1])


(4.0, 1.0)

In [14]:
pts = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
pts

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [15]:
pts.shape

torch.Size([3, 2])

In [16]:
pts = torch.zeros(3, 2)
pts

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [17]:
pts = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
pts

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [18]:
pts[0,1]

tensor(1.)

In [19]:
pts = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
pts.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.FloatStorage of size 6]

In [20]:
pts_storage = pts.storage()
pts_storage[0]

4.0

In [21]:
pts.storage()[1]


1.0

In [22]:
pts = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
pts_storage = pts.storage()
pts_storage[0] = 2.0
pts

tensor([[2., 1.],
        [5., 3.],
        [2., 1.]])

In [23]:
pts = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = pts[1]
second_point.storage_offset()

2

In [24]:
second_point.size()


torch.Size([2])

In [25]:
second_point.shape


torch.Size([2])

In [26]:
pts.stride()


(2, 1)

In [27]:
second_point = pts[1]
second_point.size()

torch.Size([2])

In [28]:
second_point.storage_offset()


2

In [29]:
second_point.stride()


(1,)

In [30]:
pts = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = pts[1]
second_point[0] = 10.0
pts

tensor([[ 4.,  1.],
        [10.,  3.],
        [ 2.,  1.]])

In [31]:
pts = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = pts[1].clone()
second_point[0] = 10.0
pts

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [32]:
pts = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
pts

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [33]:
pts_t = pts.t()
pts_t


tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [34]:
id(pts.storage()) == id(pts_t.storage())


True

In [35]:
pts.stride()


(2, 1)

In [36]:
pts_t.stride()


(1, 2)

In [37]:
some_t = torch.ones(3, 4, 5)
transpose_t = some_t.transpose(0, 2)
some_t.shape

torch.Size([3, 4, 5])

In [38]:
transpose_t.shape


torch.Size([5, 4, 3])

In [39]:
some_t.stride()


(20, 5, 1)

In [40]:
transpose_t.stride()


(1, 5, 20)

In [41]:
pts.is_contiguous()



True

In [42]:
pts_t.is_contiguous()


False

In [43]:
pts = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
pts_t = pts.t()
pts_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [44]:
pts_t.storage()


 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.FloatStorage of size 6]

In [45]:
pts_t.stride()


(1, 2)

In [46]:
pts_t_cont = pts_t.contiguous()
pts_t_cont

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [47]:
pts_t_cont.stride()


(3, 1)

In [48]:
pts_t_cont.storage()


 4.0
 5.0
 2.0
 1.0
 3.0
 1.0
[torch.FloatStorage of size 6]

In [0]:
double_pts = torch.ones(10, 2, dtype=torch.double)
short_pts = torch.tensor([[1, 2], [3, 4]], dtype=torch.short)

In [50]:
short_pts.dtype


torch.int16

In [0]:
double_pts = torch.zeros(10, 2).double()
short_pts = torch.ones(10, 2).short()

In [0]:
double_pts = torch.zeros(10, 2).to(torch.double)
short_pts = torch.ones(10, 2).to(dtype=torch.short)

In [53]:
pts_64 = torch.rand(5, dtype=torch.double)  # <1>
pts_short = pts_64.to(torch.short)
pts_64 * pts_short  # works from PyTorch 1.3 onwards

tensor([0., 0., 0., 0., 0.], dtype=torch.float64)

In [0]:
pts = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])

In [56]:
some_list = list(range(6))
some_list[:]     
some_list[1:4]   
some_list[1:]    
some_list[:4]   
some_list[:-1]  
some_list[1:4:2] 

[1, 3]

In [58]:
pts[1:]       
pts[1:, :]    
pts[1:, 0]    
pts[None]     

tensor([[[4., 1.],
         [5., 3.],
         [2., 1.]]])

In [59]:
pts = torch.ones(3, 4)
pts_np = pts.numpy()
pts_np

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [0]:
pts = torch.from_numpy(pts_np)


In [0]:
torch.save(pts, 'datapts.t')


In [0]:
with open('datapts.t','wb') as f:
   torch.save(pts, f)

In [0]:
pts = torch.load('datapts.t')


In [0]:
with open('datapts.t','rb') as f:
   pts = torch.load(f)

In [0]:
import h5py

f = h5py.File('datapts.hdf5', 'w')
dset = f.create_dataset('coords', data=pts.numpy())
f.close()

In [0]:
f = h5py.File('datapts.hdf5', 'r')
dset = f['coords']
last_pts = dset[-2:]

In [0]:
last_pts = torch.from_numpy(dset[-2:])
f.close()

In [0]:
pts_gpu = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]], device='cuda')


In [0]:
pts_gpu = pts.to(device='cuda')


In [0]:
pts_gpu = pts.to(device='cuda:0')


In [0]:
pts = 2 * pts  # <1>
pts_gpu = 2 * pts.to(device='cuda')

In [0]:
pts_gpu = pts_gpu + 4


In [0]:
pts_cpu = pts_gpu.to(device='cpu')


In [0]:
pts_gpu = pts.cuda()  
pts_gpu = pts.cuda(0)
pts_cpu = pts_gpu.cpu()

In [81]:
a = torch.ones(3, 2)
a_t = torch.transpose(a, 0, 1)

a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [82]:
a = torch.ones(3, 2)
a_t = a.transpose(0, 1)

a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [0]:
a = torch.ones(3, 2)


In [84]:
a.zero_()
a

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])